language: node_js
node_js:
  - 0.10

install:
  - npm install grunt-cli -g
  - npm install bower -g
  - sudo pip install pylint

before_script:
  - pylint --version

script:
  - pylint tools/packing.py
  - cd app && npm install && grunt test
